### ISSUE TITLE
databasemodel 설계하기

### ISSUE THREAD

**Issue by leechGamer** [yeogaemogaco/LoveYourTask---android#5]

**Comment by leechGamer** [comment]
<img width="724" alt="screen shot 2017-09-09 at 5 20 59 pm" src="https://user-images.githubusercontent.com/24830023/30238522-b39804f8-9583-11e7-8b20-c2bbcc1851d2.png">

**Comment by gyoungeunbae** [comment]
**Edit Model**
![Uploading Screen Shot 2017-09-09 at 5.20.59 PM.png…]()
